name: vg-sales-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - plotly
  - kaggle
prefix: /home/prof-adept/anaconda3/envs/vg-sales-env
